/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;
import services.IBookCategoryService;
import services.IClientService;

/**
 *
 * @author HP
 */
public class ClientView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientView
     */
    public ClientView() {
        initComponents();
        table();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Client");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //controller object 

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        catcombo = new javax.swing.JComboBox();
        imglabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        jLabel2.setText("Firstname");

        jLabel3.setText("Lastname");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Email");

        jLabel6.setText("Category");

        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        catcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Staff", "External" }));

        imglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imglabel.setText("Image");
        imglabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jButton1.setText("Upload Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reg_no", "Firstname", "Lastname", "Phone", "Email", "Photo", "Client_category"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail)
                                            .addComponent(txtphone)
                                            .addComponent(catcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveBtn)
                                        .addGap(41, 41, 41)
                                        .addComponent(updatebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addComponent(deletebtn)
                                        .addGap(16, 16, 16))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfirstname)
                                    .addComponent(txtlastname))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(catcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(updatebtn)
                            .addComponent(deletebtn))
                        .addGap(32, 32, 32)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void table() {
        Session s = util.Connection.getSessionFactory().openSession();
        Transaction tr = s.beginTransaction();
        List<models.Clients> list = s.createQuery("from Clients").list();
        tr.commit();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) table.getModel();
        model.getDataVector().removeAllElements();

        Object[] obj = new Object[7];

        for (models.Clients cl : list) {
            obj[0] = cl.getRegNo();
            obj[1] = cl.getFirstname();
            obj[2] = cl.getLastname();
            obj[3] = cl.getPhone();
            obj[4] = cl.getEmail();
            ImageIcon image = new ImageIcon(new ImageIcon(cl.getMyImage()).getImage()
                    .getScaledInstance(150, 120, Image.SCALE_SMOOTH));
            obj[5] = image;
            obj[6] = cl.getClientCategory();

            model.addRow(obj);
            System.out.println("row is displayed");

        }
        s.close();

    }
    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed
    String path;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("choose image");
        //filter ext
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if user click on save in Jchoosed
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            ImageIcon img = new ImageIcon(path);
            Image i = img.getImage();
            Image image = i.getScaledInstance(imglabel.getWidth(), imglabel.getHeight(), Image.SCALE_AREA_AVERAGING);
            imglabel.setIcon(new ImageIcon(image));
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void displayImg() {
        Session s = util.Connection.getSessionFactory().openSession();
        Transaction tr = s.beginTransaction();
        models.Clients imgNew = (models.Clients) s.get(models.Clients.class, clientId);
        byte[] bAvatar = imgNew.getPhoto();

        try {
            FileOutputStream fos = new FileOutputStream(path);
            fos.write(bAvatar);
            imglabel.setIcon(new ImageIcon(bAvatar));
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File file = new File(path);
        byte[] imageData = new byte[(int) file.length()];

        try {
            FileInputStream fileInputStream = new FileInputStream(file);
            fileInputStream.read(imageData);
            fileInputStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        models.Clients client = new models.Clients();

        client.setFirstname(txtfirstname.getText());
        client.setLastname(txtlastname.getText());
        client.setEmail(txtemail.getText());
        client.setPhone(txtphone.getText());
        client.setPhoto(imageData);
        client.setClientCategory(catcombo.getSelectedItem().toString());
        try {
            Registry registry = LocateRegistry.getRegistry(2000);
            IClientService cl = (IClientService) registry.lookup("ClientService");
            boolean result = cl.insert(client);
            System.out.println(result ? "sucess" : "fail");
            if (result) {
                JOptionPane.showMessageDialog(null, "client successfully saved");
            } else {
                JOptionPane.showMessageDialog(null, "client failed to  saved", "error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        table();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        File file = new File(path);
        byte[] imageData = new byte[(int) file.length()];

        try {
            FileInputStream fileInputStream = new FileInputStream(file);
            fileInputStream.read(imageData);
            fileInputStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        models.Clients client = new models.Clients();
        client.setRegNo(clientId);

        client.setFirstname(txtfirstname.getText());
        client.setLastname(txtlastname.getText());
        client.setPhone(txtphone.getText());
        client.setEmail(txtemail.getText());
        client.setPhoto(imageData);
        client.setClientCategory(catcombo.getSelectedItem().toString());
        try {
            Registry registry = LocateRegistry.getRegistry(2000);
            IClientService cl = (IClientService) registry.lookup("ClientService");
            boolean result = cl.update(client);
            System.out.println(result ? "sucess" : "fail");
            if (result) {
                JOptionPane.showMessageDialog(null, "client successfully updated");
            } else {
                JOptionPane.showMessageDialog(null, "client failed to  update", "error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        table();
    }//GEN-LAST:event_updatebtnActionPerformed
    int clientId;
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRow = table.getSelectedRow();
        clientId = (int) model.getValueAt(selectedRow, 0);
        txtfirstname.setText(model.getValueAt(selectedRow, 1).toString());
        txtlastname.setText(model.getValueAt(selectedRow, 2).toString());
        txtphone.setText(model.getValueAt(selectedRow, 3).toString());
        txtemail.setText(model.getValueAt(selectedRow, 4).toString());
        //imglabel.setIcon(new ImageIcon((Image) model.getValueAt(selectedRow, 5)));

        catcombo.setSelectedItem(model.getValueAt(selectedRow, 6));
    }//GEN-LAST:event_tableMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        try {
            Registry registry = LocateRegistry.getRegistry(2000);
            IClientService cl = (IClientService) registry.lookup("ClientService");
            int input = JOptionPane.showConfirmDialog(null,
                    "Do you want to delete this book category ?", "Select an Option...", JOptionPane.YES_NO_OPTION);
            // 0=yes, 1=no, 2=cancel
            System.out.println(input);
            if (input == 0) {
                boolean result = cl.delete(clientId);
                System.out.println(result ? "deleted successfully " : "failed to delete");
                JOptionPane.showMessageDialog(null, "client  deleted successfully");
            } else {
                JOptionPane.showMessageDialog(null, "operation cancelled");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        table();
    }//GEN-LAST:event_deletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox catcombo;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel imglabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
