package models;
// Generated May 13, 2020 9:22:47 AM by Hibernate Tools 4.3.1



/**
 * Bookcategory generated by hbm2java
 */
public class Bookcategory  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Bookcategory() {
    }

    public Bookcategory(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


