package models;
// Generated May 13, 2020 9:22:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name="bookcategory")
public class Books  implements java.io.Serializable {

     @Id
     @Column(name="book_id")
     private Integer bookId;
     @Column(name="title")
     private String title;
     @Column(name="author")
     private String author;
     @Column(name="pubkisher")
     private String publisher;
     @Column(name="date_of_pub")
     private Date dateOfPub;
     @Column(name="pages")
     private int pages;
     @Column(name="book_category")
     private String bookCategory;
     @Column(name="book_id")
     private int bookCategoryId;

    public Books() {
    }

    public Books(String title, String author, String publisher, Date dateOfPub, int pages, String bookCategory, int bookCategoryId) {
       this.title = title;
       this.author = author;
       this.publisher = publisher;
       this.dateOfPub = dateOfPub;
       this.pages = pages;
       this.bookCategory = bookCategory;
       this.bookCategoryId = bookCategoryId;
    }
   
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public Date getDateOfPub() {
        return this.dateOfPub;
    }
    
    public void setDateOfPub(Date dateOfPub) {
        this.dateOfPub = dateOfPub;
    }
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }
    public String getBookCategory() {
        return this.bookCategory;
    }
    
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory;
    }
    public int getBookCategoryId() {
        return this.bookCategoryId;
    }
    
    public void setBookCategoryId(int bookCategoryId) {
        this.bookCategoryId = bookCategoryId;
    }




}


