package models;
// Generated May 13, 2020 9:22:47 AM by Hibernate Tools 4.3.1



/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private Integer regNo;
     private String firstname;
     private String lastname;
     private String phone;
     private String email;
     private byte[] photo;
     private String clientCategory;

    public Clients() {
    }

    public Clients(String firstname, String lastname, String phone, String email, byte[] photo, String clientCategory) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.phone = phone;
       this.email = email;
       this.photo = photo;
       this.clientCategory = clientCategory;
    }
   
    public Integer getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(Integer regNo) {
        this.regNo = regNo;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getClientCategory() {
        return this.clientCategory;
    }
    
    public void setClientCategory(String clientCategory) {
        this.clientCategory = clientCategory;
    }




}


